version: '3'
services:
  myapi:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb/myapi_db
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
