openapi: 3.0.0
info:
  title: People API
  description: API para el manejo de personas
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /people:
    get:
      tags:
        - people
      description: Obtiene una lista de personas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
  /people/<id>:
    get:
      tags:
        - people
      description: Obtiene una persona específica
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
    post:
      tags:
        - people
      description: Crea una persona nueva
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
