# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Persona(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nombres': 'str',
        'apellidos': 'str',
        'dni': 'str'
    }

    attribute_map = {
        'nombres': 'nombres',
        'apellidos': 'apellidos',
        'dni': 'dni'
    }

    def __init__(self, nombres=None, apellidos=None, dni=None, _configuration=None):  # noqa: E501
        """Persona - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._nombres = None
        self._apellidos = None
        self._dni = None
        self.discriminator = None

        self.nombres = nombres
        self.apellidos = apellidos
        self.dni = dni

    @property
    def nombres(self):
        """Gets the nombres of this Persona.  # noqa: E501

        Nombres de la persona  # noqa: E501

        :return: The nombres of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._nombres

    @nombres.setter
    def nombres(self, nombres):
        """Sets the nombres of this Persona.

        Nombres de la persona  # noqa: E501

        :param nombres: The nombres of this Persona.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and nombres is None:
            raise ValueError("Invalid value for `nombres`, must not be `None`")  # noqa: E501

        self._nombres = nombres

    @property
    def apellidos(self):
        """Gets the apellidos of this Persona.  # noqa: E501

        Apellidos de la persona  # noqa: E501

        :return: The apellidos of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos):
        """Sets the apellidos of this Persona.

        Apellidos de la persona  # noqa: E501

        :param apellidos: The apellidos of this Persona.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and apellidos is None:
            raise ValueError("Invalid value for `apellidos`, must not be `None`")  # noqa: E501

        self._apellidos = apellidos

    @property
    def dni(self):
        """Gets the dni of this Persona.  # noqa: E501

        DNI de la persona  # noqa: E501

        :return: The dni of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni):
        """Sets the dni of this Persona.

        DNI de la persona  # noqa: E501

        :param dni: The dni of this Persona.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and dni is None:
            raise ValueError("Invalid value for `dni`, must not be `None`")  # noqa: E501

        self._dni = dni

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Persona, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Persona):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Persona):
            return True

        return self.to_dict() != other.to_dict()
