# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_persona_resource(self):
        """Test case for delete_persona_resource

        Eliminar una persona por DNI  # noqa: E501
        """
        pass

    def test_get_persona_resource(self):
        """Test case for get_persona_resource

        Obtener los detalles de una persona por DNI  # noqa: E501
        """
        pass

    def test_get_personas_resource(self):
        """Test case for get_personas_resource

        Obtener la lista de todas las personas  # noqa: E501
        """
        pass

    def test_post_personas_resource(self):
        """Test case for post_personas_resource

        Crear una nueva persona  # noqa: E501
        """
        pass

    def test_put_persona_resource(self):
        """Test case for put_persona_resource

        Actualizar los detalles de una persona por DNI  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
